### PR TITLE
Remove docs for playing around with basic authentication via the command line

### PR DESCRIPTION
**Pull request by nicomiguelino**
* Changing authentication settings can be done via the UI, so those docs could be removed.

### CODE REVIEW

**Review by vpetersson — COMMENTED** [review]
How would you even set this on Balena?

**Comment by nicomiguelino** [comment]
@vpetersson, the documentation is for user that uses Anthias that runs on top of Raspberry Pi OS Lite.
Let me add an info for that.

**Comment by vpetersson** [comment]
> @vpetersson, the documentation is for user that uses Anthias that runs on top of Raspberry Pi OS Lite. Let me add an info for that.

Right - but we probably need to overhaul the general thinking for all features to make sure they can be done in the UI.

**Comment by nicomiguelino** [comment]
@vpetersson, fair point. Thanks. I'll probably remove the documentation as setting up basic authentication in Anthias can be done in the UI, both for RPi OS and BalenaOS instances.

**Review by vpetersson — APPROVED** [review]

**Pull request merged**
