### PR TITLE
Assistance Needed with Implementing Bookworm via Balena Cloud

### PR DESCRIPTION
**Pull request by CRSBenson**
Hello,

I'm looking to create/adjust the existing repo to accept a docker build to Balena Cloud. I'm still new to learning all the ropes of docker and all, but I have gotten 'build_containers.sh' to compile the Bookworm packages. However, the process is getting hung on, "ERROR [stage-0 2/9] RUN --mount=type=cache,target=/var/cache/apt     apt-get update &&     apt-get -y install --no-install-recommends         build-essential..." Can anyone take a look at what might be going wrong here? 

I initially attempted to use VLC with Anthias running on Buster for RTSP streaming out to an HDMI. This is something that I achieved previously without Docker, so I gave it a shot and got very close, but I'm deciding to take a new approach. If using Bookworm to achieve my goals of a borderline 24/7 RTSP streaming monitor, including monitoring with Balena, isn't quite capable yet, tell me now. Otherwise, I'll continue to work with Buster on this. 

In all, I hope that this helps other developers with Anthias via Balena Cloud using Bookworm. I'm open to suggestions and willing to contribute as I learn docker during my own developments.

### CODE REVIEW

**Comment by nicomiguelino** [comment]
@CRSBenson, thank you for creating a pull request. Here are my comments:
* Bookworm introduced breaking changes.
* If you're keen on making the RSTP feature work as soon as possible, I suggest that you continue working on Buster.
* RSTP doesn't work on Buster out of the box. Meanwhile, you can check this comment from another issue: https://github.com/Screenly/Anthias/issues/1638#issuecomment-1497765335

**Comment by CRSBenson** [comment]
@nicomiguelino Thank you for the response.

I will continue to work with Buster and see if I can get something working for now. This pull request will be worked on periodically to see if we can make any progress with Balena and Bookworm.

**Comment by nicomiguelino** [comment]
@CRSBenson, I'll be trying out https://github.com/Screenly/Anthias/issues/1638#issuecomment-1497765335 on my Anthias instance running Buster (in Docker containers). Are you using a public RSTP URL. If yes, I'd like to ask for a link (for testing purposes)?

**Comment by CRSBenson** [comment]
@nicomiguelino Unfortunately, the URL is local to the subnet of the Pi. I have a bench testing station set up, so I will attempt this again. Before, I was getting a white screen, but I believe that was addressed recently, too.

**Comment by nicomiguelino** [comment]
No worries, I just found a public RTSP link from [Wowza](https://www.wowza.com/) &mdash; `rtsp://b03773d78e34.entrypoint.cloud.wowza.com:1935/app-4065XT4Z/80c76e59_stream1`. Thanks to that comment from Screenly/Anthias#1638, I was able to make RTSP working, although there were workarounds

Here's a PR for reference: #1890.

**Comment by nicomiguelino** [comment]
@CRSBenson, I will be closing this as the following pull requests were already merged:
* https://github.com/Screenly/Anthias/pull/1980
* https://github.com/Screenly/Anthias/pull/1982


If you want to update your device, you can do the following steps:
* For all platforms (whether it's Raspberry Pi OS Lite or BalenaOS), make sure to backup your data before proceeding. Click **_Settings_** on the navbar, then click **_Get Backup_**.
* For Raspberry Pi OS Lite, SSH to your device and run `bash <(curl -sL https://install-anthias.srly.io)`.
* For BalenaOS (installed via the releases or via the Raspberry Pi Imager), updates happen automatically.
* For self-deployed BalenaOS instances, see [this documentation](https://github.com/Screenly/Anthias/blob/master/docs/balena-fleet-deployment.md) for details.


Feel free to open a new issue or a new discussion if necessary.

**Pull request closed without merging**
