### PR TITLE
Fixes host agent on Bullseye

### PR DESCRIPTION
**Pull request by nicomiguelino**
#### Description

* Changes to `anthias-host-agent.service` in #1950 introduced this issue to devices running Bullseye.
* This pull request added conditional statements inside the service file template.

### CODE REVIEW

**Comment by vpetersson** [comment]
I'm not sure that I follow. Why is the environment used in one but not the other? Isn't it better to do some sort of migration to make them consistent?

**Comment by nicomiguelino** [comment]
@vpetersson, Debian versions before Bookworm (version 12) don't require the use of a virtual environment when installing Python packages via `pip`. With Debian 12, virtual environment is required, unless `--break-system-packages` is specified.

I can migrate legacy versions to use a virtual environment.

**Comment by vpetersson** [comment]
> @vpetersson, Debian versions before Bookworm (version 12) don't require the use of a virtual environment when installing Python packages via `pip`. With Debian 12, virtual environment is required, unless `--break-system-packages` is specified.
> 
> I can migrate legacy versions to use a virtual environment.

I think moving everything to virtual env/poetry will make things easier to manage.

**Comment by nicomiguelino** [comment]
@vpetersson, I agree with this.

**Review by vpetersson — APPROVED** [review]

**Pull request merged**
