### PR TITLE
Fixes video playback issue in Raspberry Pi 4.

### PR DESCRIPTION
**Pull request by nicomiguelino**
#### General

- (Temporarily) fixes Screenly/Anthias#1679.

#### Installation

```bash
cd && \
echo "export CUSTOM_BRANCH='hotfix-video-playback'" > .env && \
bash <(curl -sL https://raw.githubusercontent.com/nicomiguelino/Anthias/custom-install-1/bin/install.sh)
```

Reboot the system, SSH into the device again, then run the following:

```bash
cd ~/screenly && \
sed -i 's/pull/build/g' bin/upgrade_containers.sh && \
sudo apt-get install -y --no-install-recommends jq && \
docker compose down && \
DOCKERFILES_ONLY=1 DEV_MODE=1 ./bin/build_containers.sh && \
./bin/upgrade_containers.sh
```

### CODE REVIEW

**Comment by nicomiguelino** [comment]
@vpetersson, @salmanfarisvp
Please review.

**Comment by salmanfarisvp** [comment]
@nicomiguelino How can I run it on PI.  Do we have any updated script that I can use?

**Comment by nicomiguelino** [comment]
> @nicomiguelino How can I run it on PI. Do we have any updated script that I can use?

@salmanfarisvp, I recently edited the PR description. Please see the command there for details.
- Since Screenly/Anthias#1836 is not yet merged, you can use a Bullseye image.

**Comment by salmanfarisvp** [comment]
Hi @nicomiguelino , 

Raspberry Pi Hardware Version: **Raspberry Pi 4 Model B**
Raspberry Pi Network Setup: **Ethernet**
OS: **Raspberry Pi OS Lite (Bullseye), 64-bit**


After running the installation script, no output in the HDMI  - Just black. I think that is expected. 

> #### Installation
> ```shell
> cd && \
> echo "export CUSTOM_BRANCH='hotfix-video-playback'" > .env && \
> bash <(curl -sL https://raw.githubusercontent.com/nicomiguelino/Anthias/custom-install-1/bin/install.sh)
> ```

Then run the installation command as mentioned below. 

> Reboot the system, SSH into the device again, then run the following:
> 
> ```shell
> cd ~/screenly && \
> sed -i 's/pull/build/g' bin/upgrade_containers.sh && \
> sudo apt-get install -y --no-install-recommends jq && \
> docker compose down && \
> DOCKERFILES_ONLY=1 DEV_MODE=1 ./bin/build_containers.sh && \
> ./bin/upgrade_containers.sh
> ```

After the script, it looks good and the IP address is listed on the screen and I tested with two video types. 

✅ YouTube video links work fine 
✅ Uploaded MP4 Videos work fine. 

image

**Comment by nicomiguelino** [comment]
@salmanfarisvp, yes, that's expected (the black screen) since the MP4 video playback is currently broken for Pi 4.
Once this PR is merged, we'll never encounter the black screen again.

**Review by vpetersson — APPROVED** [review]

**Comment by salmanfarisvp** [comment]
@nicomiguelino I again tested after merging the PR with the standard installation script and it's stuck while using only WiFi as similar mentioned here https://github.com/Screenly/Anthias/issues/1846 . 

And using ethernet, it's working well and no problem was faced as it was straightforward. Great work @nicomiguelino 


 I tested with two assists. 

✅ YouTube video links work fine
✅ Uploaded MP4 Videos work fine.

**Pull request merged**
