### PR TITLE
Adds support for Raspberry Pi 5

### LINKED ISSUE #2158: Is Anthias on Raspberrypi 5 available
Hi Guys,
i have tryed to install Anthias on my RaspberryPi 5, but it didn´t works.

#### Overview of the Issue

Installed from github on RaspberryPi 5, but the script does not complete the installation.

#### Environment

* Raspberry Pi Hardware Version: Raspberrypi 5
* Raspberry Pi Network Setup: Ethernet
* Anthias Version:

### PR DESCRIPTION
**Pull request by nicomiguelino**
### Overview

- Adds support for Raspberry Pi 5
- Fixes #2158

### Checklist

- [x] Add Pi 5 support for installing Anthias on Raspberry Pi OS Lite.
- [x] Add Pi 5 support for devices running **_balenaOS_**.
- [x] Update download link for Qt and WebView binaries.

### How to test the changes?

```bash
cd && \
bash <(curl -sL https://raw.githubusercontent.com/nicomiguelino/Anthias/refs/heads/test-rpi5-support/bin/install.sh)
```

### CODE REVIEW

**Review by vpetersson — COMMENTED** [review]
I don't think this will work as the GPU is different on the pi 5.

**Comment by nicomiguelino** [comment]
@vpetersson I'm getting a Segmentation fault when running `docker` commands, so I re-installed Docker using [this guide](https://docs.docker.com/engine/install/debian/#install-using-the-repository).

The progress so far (right after running the installer, well at least some custom commands):

image

**Comment by nstephens** [comment]
Install script completes successfully on a clean install. Docker containers appear to startup correctly. However, upon reboot I lose video output altogether. No longer see any boot/kernel messages, it never returns. System is pingable, anthias service is reachable over http.

```
CONTAINER ID   IMAGE                                        COMMAND                  CREATED       STATUS                          PORTS                               NAMES     
a5c525eb3022   nicomiguelino/anthias-nginx:latest-pi5       "/usr/bin/entry.sh n…"   2 hours ago   Up 2 hours                      0.0.0.0:80->80/tcp, :::80->80/tcp   screenly-anthias-nginx-1
dab27d30fd8b   nicomiguelino/anthias-websocket:latest-pi5   "/usr/bin/entry.sh p…"   2 hours ago   Up 2 hours                                                          screenly-anthias-websocket-1
e2186bc3dab1   nicomiguelino/anthias-celery:latest-pi5      "/usr/bin/entry.sh /…"   2 hours ago   Up 2 hours                                                          screenly-anthias-celery-1
8ffd14b39755   nicomiguelino/anthias-viewer:latest-pi5      "/usr/bin/entry.sh b…"   2 hours ago   Restarting (0) 32 seconds ago                                       screenly-anthias-viewer-1
b536b74087ef   nicomiguelino/anthias-server:latest-pi5      "/usr/bin/entry.sh b…"   2 hours ago   Up 2 hours                                                          screenly-anthias-server-1
61e1a415b766   nicomiguelino/anthias-redis:latest-pi5       "/usr/bin/entry.sh r…"   2 hours ago   Up 2 hours                      127.0.0.1:6379->6379/tcp            screenly-redis-1

```

**Comment by salmanfarisvp** [comment]
Hi @nicomiguelino, I was able to install it successfully on Pi5. 

image
image

Then, I can access the dashboard page and see the splash screen on the window. 
image
image

I added a few test assets; only the audio is missing. 

- [X] PNG and other Image formats are working fine.  
- [X] Offline uploaded video working -  no audio 
- [X] Youtube link working - no audio

**Comment by nstephens** [comment]
> @nstephens, you can try running the install/update script again to see if it works on your Pi 5:
> 
> ```shell
> cd && \
> bash <(curl -sL https://raw.githubusercontent.com/nicomiguelino/Anthias/refs/heads/test-rpi5-support/bin/install.sh)
> ```

I just did a fresh install of RPi Lite OS, ran the install script, and failed quickly:

```
$ cd && \
bash <(curl -sL https://raw.githubusercontent.com/nicomiguelino/Anthias/refs/heads/test-rpi5-support/bin/install.sh)
Hit:1 http://deb.debian.org/debian bookworm InRelease
Get:2 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:3 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:4 http://archive.raspberrypi.com/debian bookworm InRelease [39.3 kB]
Reading package lists... Done
E: Release file for http://deb.debian.org/debian-security/dists/bookworm-security/InRelease is not valid yet (invalid for another 28d 8h 35min 48s). Updates for this repository will not be applied.
E: Release file for http://deb.debian.org/debian/dists/bookworm-updates/InRelease is not valid yet (invalid for another 29d 0h 38min 9s). Updates for this repository will not be applied.
E: Release file for http://archive.raspberrypi.com/debian/dists/bookworm/InRelease is not valid yet (invalid for another 28d 19h 36min 39s). Updates for this repository will not be applied.
curl: (60) SSL certificate problem: certificate is not yet valid
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
gpg: no valid OpenPGP data found.
deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *
Hit:1 http://deb.debian.org/debian bookworm InRelease
Get:2 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]        
Get:3 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Ign:4 https://repo.charm.sh/apt * InRelease
Get:5 http://archive.raspberrypi.com/debian bookworm InRelease [39.3 kB]
Ign:4 https://repo.charm.sh/apt * InRelease
Ign:4 https://repo.charm.sh/apt * InRelease
Err:4 https://repo.charm.sh/apt * InRelease
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses not yet valid certificate.  Could not handshake: Error in the certificate verification. [IP: 52.22.184.241 443]
Reading package lists... Done
E: Release file for http://deb.debian.org/debian-security/dists/bookworm-security/InRelease is not valid yet (invalid for another 28d 8h 35min 45s). Updates for this repository will not be applied.
E: Release file for http://deb.debian.org/debian/dists/bookworm-updates/InRelease is not valid yet (invalid for another 29d 0h 38min 6s). Updates for this repository will not be applied.
E: Release file for http://archive.raspberrypi.com/debian/dists/bookworm/InRelease is not valid yet (invalid for another 28d 19h 36min 36s). Updates for this repository will not be applied.
/dev/fd/63: line 80: gum: command not found
```

Manually ran sudo apt-get update and then retried the script and it worked as expected!

**Comment by nstephens** [comment]
> @nstephens, glad to hear that. About the installation issue that you encountered recently, does it happen all the time the first time you run the script (after you run a fresh install)?

I only tried the once, so unsure. Previously when I ran the install I recall it doing an apt update prior to pulling more of the script. It felt like maybe it didn't do that this time, which is why I thought to try an apt update and then re-run the script. After that it proceeded without error. I've rebooted several times and the display comes up as expected and appears operational. 

I'm running on a monitor without speakers, so I can't speak to the audio section, but the display is correct. The only nit I have (which is likely out of scope here) is that I have the RPi configured to display in portrait mode and can verify that's working by swapping to console (ctrl alt f1), however Anthias is showing everything in default landscape.

**Comment by nicomiguelino** [comment]
@nstephens, thanks for the detailed response. I'll be taking notes.
About the issues with installation and portrait mode, they will likely be addressed on separate pull requests.

**Review by vpetersson — APPROVED** [review]

**Pull request merged**
