### PR TITLE
Youtube dl to yt dlp

### PR DESCRIPTION
**Pull request by schwingm**

### CODE REVIEW

**Comment by schwingm** [comment]
Fixes https://github.com/Screenly/Anthias/issues/1779

**Comment by vpetersson** [comment]
Thanks @schwingm. 
Can you please review and test this @nicomiguelino?

**Comment by nicomiguelino** [comment]
Great work! @schwingm

@schwingm, @vpetersson
I tested this on a Raspberry Pi 4 (Model B) running a 64-bit Raspberry Pi OS Lite (Bullseye). It's working &mdash; Anthias is able to download the videos on the device.

There's one front-end nitpick though &mdash; After saving the URL asset (which is a YouTube link), the Activity (status) of the asset stays at "Asset in processing", unless the page's refreshed.

image

**Review by nicomiguelino — COMMENTED** [review]
Looks like it's working, but there's still problems with the websocket.

**Comment by nicomiguelino** [comment]
Thanks too! Got the same error on a Pi 3 B+ (using a 64-bit Bullseye). Let me try the changes if it'll work.

**Comment by nicomiguelino** [comment]
@schwingm, I tried `send_string`. Looks like the error is gone.

```
screenly-anthias-server-1  | Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
screenly-anthias-server-1  |                     You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
screenly-anthias-server-1  | Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
screenly-anthias-server-1  |                     You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
screenly-anthias-server-1  | Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
screenly-anthias-server-1  |                     You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
screenly-anthias-server-1  | [youtube] Extracting URL: https://www.youtube.com/watch?v=LXb3EKWsInQ
screenly-anthias-server-1  | [youtube] LXb3EKWsInQ: Downloading webpage
screenly-anthias-server-1  | [youtube] LXb3EKWsInQ: Downloading ios player API JSON
screenly-anthias-server-1  | [youtube] LXb3EKWsInQ: Downloading android player API JSON
screenly-anthias-server-1  | [youtube] LXb3EKWsInQ: Downloading m3u8 information
screenly-anthias-server-1  | [info] LXb3EKWsInQ: Downloading 1 format(s): 22
screenly-anthias-server-1  | [download] Destination: /data/screenly_assets/339e309a0e6c498d97707f06ca968e94
[download] 100% of   60.93MiB in 00:00:09 at 6.60MiB/s




screenly-anthias-server-1  | Remote Git branch not available
screenly-anthias-server-1  | Unable to get latest version from GitHub
```

However, a manual page refresh is still needed before enabling the newly-added YouTube asset (as it still displays "Asset in processing").

**Review by nicomiguelino — APPROVED** [review]

**Comment by nicomiguelino** [comment]
@schwingm, I already merged this PR since your changes worked.
The follow-up fixes that you mentioned before can be put in a separate PR.

**Pull request merged**
